import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProviderWrapper from "./ProviderWrapper";
import { ReactNode } from 'react';

interface ProviderWrapperProps {
  children: ReactNode;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Chatbot Demo Web App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ProviderWrapperProps) {
  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ProviderWrapper>
            {children}
          </ProviderWrapper>
        </body>
    </html>
  );
}
