import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProviderWrapper from "./ProviderWrapper";
import { ReactNode } from 'react';
import i18nConfig from "../../../i18nConfig";
import initTranslations from "../i18n";
import { dir } from 'i18next';
import TranslationsProvider from "../components/TranslationsProvider";
import { ToastContainer } from "react-toastify";
import ThemeSwitcher from "../components/ThemeSwitcher";

interface RootLayoutProps {
  children: ReactNode;
  params: {
    locale: string;
  };
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Chatbot Demo Web App",
  description: "Generated by create next app",
};

const i18nNamespaces = ['ChatbotDemoWebApp'];

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

const RootLayout = async ({ children, params}: RootLayoutProps) => {
  const { locale } = await params;
  const { t, resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang={locale} dir={dir(locale)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TranslationsProvider resources={resources} locale={locale} namespaces={i18nNamespaces}>
          <ProviderWrapper>
            {children}
          </ProviderWrapper>
        </TranslationsProvider>
      </body>
    </html>
  );
}

export default RootLayout
